language: python
sudo: required

branches:
  only:
    - master

before_install:
  - echo "Installing linter"
  - pip install pycodestyle

jobs:
  include:
    - stage: Lint
      script:
        - pycodestyle .
